import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import { League_Spartan } from "next/font/google" 
import "./globals.css";
import Header from "./_components/Header";

const leagueSpartan = League_Spartan({
  subsets: ["latin"],
  display: "swap"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${leagueSpartan.className} h-[100vh] bg-[hsl(180,52%,96%)]`}
      >
        <Header/>
        <main className="mt-10 pb-4 px-8">
          {children}
        </main>
      </body>
    </html>
  );
}
